language: node_js
sudo: required
cache: yarn
env:
  global:
  - ENCRYPTION_LABEL: "9bd6be56f5a3"
  - COMMIT_AUTHOR_EMAIL: "priley86@gmail.com"
  - COMMIT_AUTHOR_USERNAME: "priley86"
  - TRIGGER_REPO_SLUG: "priley86/patternfly-react-monorepo"
  - TRIGGER_REPO_BRANCH: "master"
notifications:
  email: false
before_install:
- .travis/before_install.sh
- yarn install
script:
- yarn test
- yarn coveralls
after_success:
- .travis/after_success.sh
- .travis/release.sh
git:
  depth: 1
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
